summachar/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quizportal.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quizportal/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    ROLES = (
        ('A', 'Admin'),
        ('U', 'User')
    )
    role = models.CharField(max_length=1, choices=ROLES)
    mobile = models.CharField(max_length=10)


class Test(models.Model):
    test_name = models.CharField(max_length=30, unique=True)
    test_date = models.DateTimeField(null=True)
    start = models.BooleanField(default=False)
    status = models.BooleanField(default=False)
    slug = models.SlugField(null=True)

    def __str__(self):
        return self.test_name


class Question(models.Model):
    select_test = models.ForeignKey(Test, on_delete=models.CASCADE, related_name='que')
    text_question = models.CharField(max_length=300, null=True,blank=True)
    img_question = models.ImageField(null=True, blank=True)


class Option(models.Model):
    select_question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='opts')
    select_option = models.CharField(max_length=30)
    option_status = models.BooleanField(default=False)

    def __str__(self):
        return self.select_option


class UserAttempts(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='answers')
    test = models.ForeignKey(Test, on_delete=models.CASCADE, related_name='answers')

    unique_together = [['user', 'test']]

    def __str__(self):
        return self.user.first_name + '-' + self.test.test_name


class UserResponses(models.Model):
    attempt = models.ForeignKey(UserAttempts, on_delete=models.CASCADE, related_name='response')
    omr_question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='question')
    answer = models.ForeignKey(Option, on_delete=models.SET_NULL, null=True, blank=True)

templates/admin_homepage.html
<!doctype html>
<html lang="en">
  <head>
      {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/homepage.css' %}">
    <title>HomePage</title>
    
  </head>
  <body>
    <div class="container">
        <div class="row mx-auto">
            <div class="main-div mx-auto col-md-5" style="padding-top: 30px;">
                <div class="main-content">
                    <nav class="navbar navbar-expand-lg navbar-light bg-light">
                        <div class="container-fluid">
                            <a class="navbar-brand mx-2"><img src="{% static 'images/summachar.png' %}"></a>
                        </div>
                        <form class="d-flex mx-2">
                            {% if request.user.is_authenticated %}
                            <h6 style="margin: 0;">{{ request.user.first_name }}</h6>
                            {% else %}
                            <a href="{% url 'login_option' %}" style="text-decoration: none;"><b>Login</b></a>
                            {% endif %}
                            </form>
                    </nav>
                    <div class="heading m-3">
                        {% if request.user.is_authenticated %}
                        <h6 style="margin: 0;" class="mb-3">Welcome Admin</h6>
                        {% else %}
                        <h6>Please <a href="{% url 'login_page' %}" style="text-decoration: none;"><b>Login</b></a> before you Continue</h6>
                        {% endif %}
                        {% if test %}
                        <a href="{% url 'test_page' %}" class="btn btn-outline-warning mb-3">Go to tests</a>
                        {% else %}
                        <h3 style="color: red;">No Scheduled Tests</h3>
                        {% endif %}
                        <a href="{% url 'schedule_test' %}" class="btn btn-outline-dark mb-3">Schedule a Test</a>
                        <a href="{% url 'user_logout' %}" class="btn btn-outline-info mx-2 mb-3" style="fluid: right;">Logout</a>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
    
    <!--PopOver-->
    <script>
        
        var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
        var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
            alert("Hy")
        return new bootstrap.Popover(popoverTriggerEl)
        });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

templates/answer.html
<!doctype html>
<html lang="en">
  <head>
      {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/answer.css' %}">
    <title>Report</title>
    
  </head>
  <body>
    <div class="container">
        <div class="row mx-auto">
            <div class="main-div mx-auto col-md-5" style="padding-top: 30px;">
                <div class="main-content">
                    <h1 class="text-center"><img src="{% static 'images/summachar.png' %}"></h1>
                    <h4 class="mx-3 my-2">Test - <span style="color: red;">{{ response.first.attempt.test }}</span></h4>
                    <h4 class="mx-3 my-2">User - <span style="color:green">{{ response.first.attempt.user.first_name }}</span></h4>
                      <div class="mx-5 my-3">

                        <table border="1" style="width: 100%;" class="mb-3">
                            <tr>
                                
                                <th>Question</th>
                                <th>Answer</th>
                            </tr>
                            {% for i in response %}
                            <tr>
                                <td>{{ i.omr_question.text_question }}</td>
                                <td>{{ i.answer.select_option }}</td>
                            </tr>
                            {% endfor %}
                           
                        </table>
                          
                         <a href="{% url 'admin_homepage' %}" class="btn btn-outline-success">Home</a>   
                      </div>
                        
                    
                    
                </div>
            </div>
        </div>
    </div>
    

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

templates/complete.html
<!doctype html>
<html lang="en">
  <head>
      {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/cong.css' %}">
    <title>Congratulations</title>
    
  </head>
  <body>
    <div class="container">
        <div class="row mx-auto">
            <div class="main-div mx-auto col-md-5" style="padding-top: 90px;">
                <div class="main-content">
                    <h1 class="text-center"><img src="{% static 'images/summachar.png' %}"></h1>
                    <div class="text-center" style="justify-content: center; align-items: center;">
                        <img src="{% static 'images/cong.png' %}">
                        <h6>Thanks for giving the test !!</h6>
                        <h5 class="">Go <a href="{% url 'user_homepage' %}" style="text-decoration: none;"><b>Home</b></a></h5>
                    </div>
                   
                </div>
            </div>
        </div>
    </div>
    

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

templates/cong.html
<!doctype html>
<html lang="en">
  <head>
      {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/cong.css' %}">
    <title>Congratulations</title>
    
  </head>
  <body>
    <div class="container">
        <div class="row mx-auto">
            <div class="main-div mx-auto col-md-5" style="padding-top: 90px;">
                <div class="main-content">
                    <h1 class="text-center"><img src="{% static 'images/summachar.png' %}"></h1>
                    <div class="text-center" style="justify-content: center; align-items: center;">
                        <img src="{% static 'images/cong.png' %}">
                        <h6>Congratulations you have successfully Signed Up !!</h6>
                        <h5 class="">Now <a href="{% url 'login_page' %}" style="text-decoration: none;"><b>Login</b></a> here</h5>
                    </div>
                   
                </div>
            </div>
        </div>
    </div>
    

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

templates/exam.html
<!doctype html>
<html lang="en">
  <head>
      {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/homepage.css' %}">
    <title>Exam</title>
  </head>
  <body>
    <div class="container-fluid">
        <div class="row mx-auto">
            <h1 class="text-center my-2">Good Luck !</h1>
            <h2 style="color: darkblue;" class="mb-3">   {{ test }}  </h2>
            <form method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              {% for i in test.que.all %}
              <input type="hidden" name="question" value="{{ i.pk }}">
              <p><b>{{ forloop.counter }}.</b> 
                {% if i.img_question %}
                <img src="{{ i.img_question.url }}" class="img-fluid">
                {% elif i.text_question %}
                {{ i.text_question }}
                {% endif %}
              </p>
              {% for j in i.opts.all %}
              <p><input type="radio" name="answer-{{ i.pk }}" value="{{ j.pk }}">{{ j.select_option }}</p>
              {% endfor %}
              {% endfor %}
             <input type="submit" class="btn btn-primary" value="Submit">
            </form>
            </div>
        </div>
    </div>
    
    <!--PopOver-->

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
<!doctype html>
<html lang="en">
  <head>
      {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <title>Summachar</title>
  </head>
  <body>
     <div class="container">
         <div class="row" style="padding-top: 80px;">
            <div class="main-div my-4"> 
             <div class="main-content">
                 <div class="text-center">
                    <h1 style="background-color: rgb(255, 255, 255);"><img src="{% static 'images/summachar.png' %}"></h1>
                 </div>
                 <div class="row login-options text-center">
                     <div class="col-md-5 col-3 text-center admin-button">
                        <a href="{% url 'signup_page' %}?role=admin">Signup as Admin</a>
                     </div>
                     <div class="col-md-5 col-3 text-center user-button">
                        <a href="{% url 'signup_page' %}?role=user">signup as user</a>
                     </div>
                     <h5>Already have an account ? <a href="{% url 'login_page' %}"><b> Login </b></a> here</h5>
                 </div>
             </div>
            </div>
         </div>
     </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    
    
    
  </body>
</html>

templates/schedule_test.html
<!doctype html>
<html lang="en">
  <head>
      {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/schedule_test.css' %}">
    <title>Schedule_test</title>
  </head>
  <body>
   
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
                  <a class="navbar-brand" href="#"><img src="{% static 'images/summachar.png' %}" style="width: 25%;"></a>
                  
                    <div class="d-flex">
                      {% if request.user.is_authenticated %}
                      <a href="" style="text-decoration: none;"><b>{{ request.user.first_name }}</b></a>
                      {% else %}
                      <a href="" style="text-decoration: none;"><b>Login</b></a>
                      {% endif %}
                    </div>
                  </div>
              </nav>
              <div class="container">
                  <div class="row">

                    <h3>Schedule Test !!</h3>
                     
                     <div class="col-md-4 test-area">
                         <div class="text-center">
                             <h4 class="my-2">Test</h4>
                         </div>
                         <form class="row my-3" method="POST">
                             {% csrf_token %}
                             <div class="col-md-5">
                                 {{ t_form.test_name }}
                             </div>
                             <div class="col-md-4">
                                {{ t_form.test_date }}
                             </div>
                             <div class="col-md-2">
                                 <input type="submit" class="btn btn-success" value="Add" name="test-submit">
                             </div>
                         </form>
                         <hr>
                         {% for i in test %}
                         <a href="{% url 'schedule_test' %}?test={{ i.slug }}" style="text-decoration: none; color: rgb(134, 134, 134);">
                         <div class="test-name my-2" id="{{ forloop.counter }}test">
                             <h5>{{ i.test_name }}</h5>
                         </div>
                         </a>
                         {% endfor %}
                     </div>

                     <div class="col-md-4 question-area">
                         
                         <div class="text-center">
                             <h3 class="my-2">Questions</h3>
                         </div>
                         
                         <form class="row my-3" method="POST" enctype="multipart/form-data">
                             {% csrf_token %}
                             <input type="hidden" value="{{  this_test.pk }}" name="select_test" style="display: none;">
                             <div class="col-md-7">
                                {{ q_form.errors.as_text }}
                                 <div class="row">
                                    <div class="col-md-9 image-section" id="image-section">
                                        
                                        <div class="profile-pic-div">
                                            <img style="max-width: 200px;max-height: 200px;" src='{%  static "images\q.jpg" %}' id="photo" name="profile_pic">
                                             <span style="display: none;">{{ q_form.img_question }}</span>
                                            
                                              <span class="text-danger">{{ q_form.img_question.errors.as_text }}</span>
                                            <label for="id_img_question" id="uploadBtn">Select Image</label>
                                          </div>
    
                                    </div>
                                    
                                    <h6 class="mt-2">Or</h6>
                                    <div class="col-md-12">
                                       {{ q_form.text_question }}
                                       {{ q_form.text_question.errors.as_text }}
                                   </div>
                                 </div>
                             </div>   
                            <div class="col-md-2">
                                <input type="submit" class="btn btn-success" value="Add Question" name="question-submit">
                            </div>
                         </form>
                         <hr>
                         <h6 class="my-3">{% if this_test.test_name %} {{ this_test.test_name }} {% else %} None : {% endif %}(Selected Test)</h6>
                         {% for j in this_test.que.all %}
                         <div class="test-name my-2" id="{{ j.pk }}test">
                            <a href="{% url 'schedule_test' %}?test={{ this_test.slug }}&question={{ j.pk }}" style="text-decoration: none; color: rgb(54, 54, 54);"><h5>Q-{{ forloop.counter }} : {% if j.img_question %}<img src="{{ j.img_question.url }}" style="width: 300px; height: 300px;"></a>
                                {% else %}{{ j.text_question }} {% endif %}</h5></a>
                         </div>
                         {% endfor %}
                    </div>

                    <div class="col-md-4">
                        <div class="text-center">
                            <h4 class="my-2">Options</h4>
                        </div>
                        <form class="row my-3" method="POST">
                            {% csrf_token %}
                            <input type="hidden" value="{{  this_question.pk }}" name="select_question" style="display: none;">
                            {{ o_form.errors.as_text }}
                            <div class="col-md-3">
                                {{ o_form.option_status }}<br>

                                <span>(select if answer is correct)</span>
                            </div>
                            <div class="col-md-7">
                                {{ o_form.select_option }}
                                <span class="text-danger">{{ o_form.select_option.errors.as_text }}</span>
                            </div>
                            <div class="col-md-2">
                                <input type="submit" class="btn btn-success" value="Add Option" name="option-submit">
                            </div>
                        </form>
                        <hr>
                         <h6 class="my-3">{% if this_question.text_question %} {{ this_question.text_question }} {% elif this_question.img_question %} <img src="{{ this_question.img_question.url }}" style="width: 250px; height:250px;"> {% else %} None : {% endif %}(Selected Question)</h6>
                        <ol type="1">
                            {% for k in this_question.opts.all %}
                               {% if k.option_status == True %}
                               <li style="color: green;">{{ k.select_option }}</li>
                               {% else %}
                               <li style="color: rgb(235, 55, 0);">{{ k.select_option }}</li>
                               {% endif %}
                               {% endfor %}
                        </ol>
                        <a href="{% url 'test_page' %}" class="done-button btn btn-outline-primary"><h3>DONE</h3></a>
                         
                    </div>      
                 
                
                </div>
           
           
           
                </div>

    
            <script src="https://code.jquery.com/jquery-3.6.0.js"
             integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous">
            </script>
    


    <script>
       
        const imgDiv = document.querySelector('.profile-pic-div');
 const img = document.querySelector('#photo');
 const file = document.querySelector('#id_img_question');
 const uploadBtn = document.querySelector('#uploadBtn');
 
 
 
 
 
 file.addEventListener('change', function(){
    
     const choosedFile = this.files[0];
 
     if (choosedFile) {
 
         const reader = new FileReader(); 
 
         reader.addEventListener('load', function(){
             img.setAttribute('src', reader.result);
         });
 
         reader.readAsDataURL(choosedFile);
 
         
     }
 });
 
 
 
     </script>

    <script>
       $(document).ready(function(){
           $('.image-section').show();
           $('Show-Image').click(function(){
               $('.image-section').show();
           });
       });
    </script>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    
  </body>
</html>